# Generated by Django 4.2.7 on 2023-11-23 20:26

from django.db import migrations


def add_product(apps, schema_editor):
    product_model = apps.get_model('product', 'Product')
    product_model.objects.create(name='T-shirt')
    product_model.objects.create(name='Hoodie')


class Migration(migrations.Migration):
    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_product),
    ]
